package com.falcon.ipc.runtime

import android.os.Bundle
import com.falcon.ipc.protocol.ErrorCode
import com.falcon.ipc.protocol.IpcEnvelope
import com.falcon.ipc.transport.IpcTransport

/** Server-side typed dispatch generated by KSP per @IpcService. */
interface IpcDispatcher {
    fun dispatch(methodId: Int, args: Bundle): Bundle
    fun eventFlow(methodId: Int): kotlinx.coroutines.flow.Flow<Bundle>? = null
    /**
     * Invoke an @IpcCallback method. The [reply] channel carries a full
     * [IpcEnvelope] so both success (onResult) and error (onError) replies
     * can be delivered back to the caller. The default body handles an
     * unmatched methodId (older server / multi-app) by replying METHOD_NOT_FOUND.
     */
    fun invokeCallback(methodId: Int, args: Bundle, reply: (IpcEnvelope) -> Unit) {
        reply(IpcEnvelope.error(ErrorCode.METHOD_NOT_FOUND, "No callback for methodId $methodId"))
    }
}

/** Aggregated factories generated by KSP per compilation module. */
interface FalconGeneratedRegistry {
    val dispatcherFactories: Map<String, (Any) -> IpcDispatcher>
    val proxyFactories: Map<String, (IpcTransport, String) -> Any>
    /**
     * Per-service wire-contract hash, checked once at discovery to reject a client and server
     * built from different interface/Parcelable definitions. Defaults to empty for backward
     * compatibility with registries generated before this field existed (no check performed).
     */
    val interfaceSchemas: Map<String, Int> get() = emptyMap()
}
