package com.falcon.ipc.runtime

import android.os.Bundle
import com.falcon.ipc.transport.IpcTransport

/** Server-side typed dispatch generated by KSP per @IpcService. */
interface IpcDispatcher {
    fun dispatch(methodId: Int, args: Bundle): Bundle
    fun eventFlow(methodId: Int): kotlinx.coroutines.flow.Flow<Bundle>? = null
    fun invokeCallback(methodId: Int, args: Bundle, reply: (Bundle) -> Unit) {}
}

/** Aggregated factories generated by KSP per compilation module. */
interface FalconGeneratedRegistry {
    val dispatcherFactories: Map<String, (Any) -> IpcDispatcher>
    val proxyFactories: Map<String, (IpcTransport, String) -> Any>
}
